<?php include "header-health.php"; ?>
    <div class="container">
    <h1 style="margin:4rem  6rem 3rem;" class="titel-h1">How To be Healthy</h1>
    <div class="image-secion">
        <img width="100%" height="500px" src="./food/image/Woman chopping vegetables.jpg" alt="">
    </div>
    <div class="article">
        <div class="hsf-paragraph-component">
            <p>Eating a healthy, balanced diet is one of the most important things you can do to protect your health. In fact, up to 80% of premature heart disease and stroke can be prevented through your life choices and habits, such as eating a healthy diet and being physically active.

                A healthy diet can help lower your risk of heart disease and stroke by:</p>
                <ul>
                    <li>improving your cholesterol levels</li>
                    <li>
                        reducing your blood pressure
                    </li>
                    <li>
                        helping you manage your body weight
                    </li>
                    <li>
                        controlling your blood sugar.
                    </li>
                </ul>
                <h6>What does a healthy, balanced diet look like?</h6>
                <p>
                    Canada’s Food Guide recommends eating a variety of healthy foods each day. This includes eating plant-based foods more often and choosing highly-processed or ultra-processed foods less often.
                </p>
        </div>
    </div>
</div>
<?php include "footer.php"; ?>